### PR TITLE
Change ColorPickerDialog.Show to return null Color when dialog is cancelled, instead of the default color

### PR DESCRIPTION
**Pull request by mfeingol**
This makes it possible to distinguish between the user liking the default color, and the user cancelling.

This is a breaking change.

### CODE REVIEW

**Comment by galadril** [comment]
Thanks!

**Comment by mfeingol** [comment]
Thanks for the merge! Would be nice to see a NuGet update with this at some point. :-)

**Comment by galadril** [comment]
Done (it was late yesterday)

**Comment by galadril** [comment]
v1.0.7

**Comment by mfeingol** [comment]
Many thanks!

**Comment by galadril** [comment]
Thanks for your contribution

**Pull request merged**
